version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    volumes:
      - ./dynamodb_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1
      - DYNAMO_DB_ENDPOINT=http://dynamodb:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - dynamodb
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: npm run dev

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    restart: unless-stopped
